added Stagger feature
specify initial delay (ms) in order to stagger playback of several
videos.

diff --git a/makevideo b/makevideo
--- a/makevideo
+++ b/makevideo
@@ -20,37 +20,49 @@ cp $PICO_SDK_PATH/external/pico_sdk_import.cmake ./
 re='^[+]?[0-9]+([.][0-9]+)?$'
 if [[ $1 == "" ]] || [[ $1 == "0" ]] || ! [[ $1 =~ $re ]]; then
   echo "error: framerate not a number" >&2
-  echo "usage: makevideo.sh FRAMERATE MODE [OVERCLOCK] [images]" >&2
+  echo "usage: makevideo FRAMERATE STAGGER MODE [OVERCLOCK] [images]" >&2
   exit 1
 fi
 echo "* Requested framerate: "$1" fps"
 echo "#define FRAMERATE "$1 > ./Framerate.h
 
 
-if [[ $2 == "" ]] || [[ $2 != "0" ]] && [[ $2 != "1" ]] && [[ $2 != "2" ]]; then
+# Stagger
+# $2, values range 0-inf integer.
+re='^[+]?[0-9]+([.][0-9]+)?$'
+if [[ $2 == "" ]] || ! [[ $2 =~ $re ]]; then
+  echo "error: stagger value not a number" >&2
+  echo "usage: makevideo FRAMERATE STAGGER MODE [OVERCLOCK] [images]" >&2
+  exit 1
+fi
+echo "* Stagger: "$2" ms"
+echo "#define STAGGER "$1 >> ./Framerate.h
+
+
+# Compilation mode: no compression, simple compression, blokweave compression.
+if [[ $3 == "" ]] || [[ $3 != "0" ]] && [[ $3 != "1" ]] && [[ $3 != "2" ]]; then
   echo "error: Invalid compilation mode." >&2 
   echo "0: Raw data. Largest binary size, highest framerate." >&2
   echo "1: Single frame compression." >&2
   echo "2: Blokweave compression. Highest possible compression. Smallest binary, lowest framerate." >&2
-  echo "usage: makevideo.sh FRAMERATE MODE [OVERCLOCK] [images]" >&2
+  echo "usage: makevideo FRAMERATE STAGGER MODE [OVERCLOCK] [images]" >&2
   exit 1
 fi
-echo "* Choosing frame compilation mode: "$2
-
+echo "* Choosing frame compilation mode: "$3
 
 
 # Overclock options
 re='^[0-9]+$'
-if [[ $3 =~ $re ]]; then
-  imgparam=4
-  if [[ $3 == "0" ]]; then
+if [[ $4 =~ $re ]]; then  # if $4 contains a valid overclock value;
+  imgparam=5
+  if [[ $4 == "0" ]]; then
     overclock="0"
   else
     overclock="1"
   fi
 else
   overclock="0"
-  imgparam=3
+  imgparam=4
 fi
 if [[ $overclock == "0" ]]; then
   echo "* Standard processor speed: 133 MHz"
@@ -66,9 +78,9 @@ echo
 echo "* Compiling images into ImageDataRaw.c and ImageDataRaw.h byte array files..."
 if [[ "" == "${@:$imgparam}" ]]; then
     if [[ -d $(cat IMGS_PATH) && ! -z $(ls -A $(cat IMGS_PATH)) ]]; then	
-	python3 bytearray.py $(cat IMGS_PATH)*
+	python3 bytearray.py $(cat IMGS_PATH)*.png
     else
-	python3 bytearray.py ./imgs/*
+	python3 bytearray.py ./imgs/*.png
     fi
 else
     python3 bytearray.py ${@:imgparam}
